Repository fack2/Sawaah-, pull requests merged in 2019-11, with the labels that each got.

#17 Shared component/Button #6
  client/Sawaah/src/Components/SharedComponent/Button/index.js
  client/Sawaah/src/Components/SharedComponent/Button/index.style.js
Labels: approved

#22 Create database #21
  client/Sawaah/.travis.yml
  server/database/db_build.js
  server/database/db_build.sql
  server/database/db_connection.js
  server/database/fakeData.sql
Labels: changes-requested

#28 Edited the background color
  client/Sawaah/src/assets/images/airplane-logo.png
Labels: awaiting-review

#27 Shared component search result
  client/Sawaah/ScreenNavigator.js
  client/Sawaah/src/Components/Layout/SearchResult/index.js
  client/Sawaah/src/Components/Layout/SearchResult/index.style.js
  client/Sawaah/src/Components/SharedComponent/SearchResult/index.js
  client/Sawaah/src/Components/SharedComponent/SearchResult/index.style.js
  client/Sawaah/src/assets/images/arrive.png
  client/Sawaah/src/assets/images/departure.png
Labels: awaiting-review

#29 Editied on Landing page
  client/Sawaah/src/Components/Layout/LandingPage/index.js
Labels: awaiting-review

#26 Layout/destination
  client/Sawaah/ScreenNavigator.js
  client/Sawaah/src/Components/Layout/Destination/index.js
  client/Sawaah/src/Components/Layout/Destination/index.style.js
  client/Sawaah/src/Components/SharedComponent/NavBar/index.js
  client/Sawaah/src/actions/index.js
  client/Sawaah/src/reducers/index.js
Labels: changes-requested

#30 Backend query/get destination data
  server/database/db_build.sql
  server/database/fakeData.sql
  server/database/queries/getDestinationData.js
Labels: changes-requested

#34 Layout/signup #14
  client/Sawaah/App.js
  client/Sawaah/ScreenNavigator.js
  client/Sawaah/src/Components/Layout/LandingPage/index.js
  client/Sawaah/src/Components/Layout/Signup/index.js
  client/Sawaah/src/Components/Layout/Signup/index.style.js
  client/Sawaah/src/Popups/Login/index.js
  client/Sawaah/src/Popups/Login/index.style.js
  client/Sawaah/src/Popups/Signup/index.js
  client/Sawaah/src/Popups/Signup/index.style.js
  client/Sawaah/src/actions/defaultAppActions.js
  client/Sawaah/src/actions/signupLoginActions.js
  client/Sawaah/src/reducers/defaultAppReducer.js
  client/Sawaah/src/reducers/signupLoginReducer.js
Labels: awaiting-review

#36 Made changes to signup
  client/Sawaah/src/Components/Layout/Signup/index.js
  client/Sawaah/src/Components/Layout/Signup/index.style.js
Labels: Done, approved

#33 Made Login page in front-end #15
  client/Sawaah/ScreenNavigator.js
  client/Sawaah/src/Components/Layout/Login/index.js
  client/Sawaah/src/Components/Layout/Login/index.style.js
  client/Sawaah/src/actions/signupLoginActions.js
  client/Sawaah/src/reducers/defaultAppReducer.js
  client/Sawaah/src/reducers/signupLoginReducer.js
Labels: awaiting-review

#32 Made a profile page #12
  client/Sawaah/ScreenNavigator.js
  client/Sawaah/src/Components/Layout/Profile/index.js
  client/Sawaah/src/Components/Layout/Profile/index.style.js
  client/Sawaah/src/assets/images/PA-logo.gif
  client/Sawaah/src/assets/images/barcode.png
  client/Sawaah/src/assets/images/left-arrow.svg
  client/Sawaah/src/assets/images/plane.png
  client/Sawaah/src/assets/images/profile.png
  client/Sawaah/src/assets/images/profileImg.png
Labels: awaiting-review
